### ISSUE TITLE
'vim.vm.device.VirtualEthernetCard.DistributedVirtu' object has no attribute 'deviceName'

### ISSUE THREAD

**Issue by zaxos** [mikeSimos/vsphere_ansible_inventory#3]
Hi Mike,

In my environment, the inventory script fails with:

`[xxx@yyy vsphere_ansible_inventory]$ ansible all -i vsphere_inventory.py -m ping
ERROR! Attempted to execute "vsphere_inventory.py" as inventory script: Inventory script (vsphere_inventory.py) had an execution error: Traceback (most recent call last):
  File "/etc/ansible/vars/vsphere_ansible_inventory/vsphere_inventory.py", line 297, in <module>
    main()
  File "/etc/ansible/vars/vsphere_ansible_inventory/vsphere_inventory.py", line 292, in main
    data = v.cached_inventory(filters, cache_path=cache_path, cache_ttl=cache_ttl, refresh=args.reload_cache)
  File "/etc/ansible/vars/vsphere_ansible_inventory/vsphere_inventory.py", line 208, in cached_inventory
    return self.list_and_save(filters, cache_path)
  File "/etc/ansible/vars/vsphere_ansible_inventory/vsphere_inventory.py", line 170, in list_and_save
    data = self.list_inventory(filters)
  File "/etc/ansible/vars/vsphere_ansible_inventory/vsphere_inventory.py", line 87, in list_inventory
    self.append_vm_info(vm)
  File "/etc/ansible/vars/vsphere_ansible_inventory/vsphere_inventory.py", line 109, in append_vm_info
    net.append(dev.backing.deviceName)
AttributeError: 'vim.vm.device.VirtualEthernetCard.DistributedVirtu' object has no attribute 'deviceName'`

From the error message, I guess it has something to do with the fact that I use distributed switch. My vCenter version is 6.0U2a.

Thanks.

**Comment by mikesimos** [comment]
Thank you!
